### ISSUE TITLE
Xfce-Desktop Wallpaper update doesn't work with multiple workspaces

### ISSUE THREAD

**Issue by prabhpreet** [markubiak/wallpaper-reddit#17]
Hi, this is what I get when I try to update my wallpaper using wallpaper-reddit:
```
wallpaper-reddit getmotivated
searching for valid images...
downloading http://imgur.com/xclHvfN.jpg
Property "/backdrop/screen0/monitor0/image-show" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.
Property "/backdrop/screen0/monitor0/image-path" does not exist on channel "xfce4-desktop". If a new property should be created, use the --create option.
wallpaper set command was run
```
I'm using Arch Linux. Apparently instead of the `/backdrop/screen0/monitor0/image-path` property, there is a `backdrop/screen0/monitor0/workspace0/last-image` property which doesn't work.

A manual fix was to locate the `~/.wallpaper` folder and use that as the desktop wallpaper folder setting.

**Comment by markubiak** [comment]
Alright, I've got a possible fix up on the dev branch.  If you can confirm that it fixes your system, I'll close the bug.

**Comment by prabhpreet** [comment]
It's fixed :+1: Thank you :)

**Comment by markubiak** [comment]
No problem.  I'm gonna close it and update the main branch with a new release (AUR update/packages).  Thanks for the bug report!
