### ISSUE TITLE
Make --startup flag to run the script at startup

### ISSUE THREAD

**Issue by lalo2302** [markubiak/wallpaper-reddit#21]
I think it would be cool to only run the program once, and so every time you start the computer you will have a new wallpaper

**Comment by markubiak** [comment]
I'm sorry, I'm not quite sure what you're asking here.  The --startup flag does, in fact, run the program in a mode designed for the start of a computer.  It waits until a network connection is established, and then runs the script as normal.  I personally have an entry in ~/.config/autostart for the script, and so every time I log into my computer I get a new wallpaper.

**Comment by lalo2302** [comment]
I was thinking that the flag could put the entry so it can autostart without doing something else

**Comment by markubiak** [comment]
I like this, and I can certainly do it for Linux.  I do not think that the default --startup flag should create the autostart file though, maybe create a new flag "--auto-startup"?

**Comment by lalo2302** [comment]
That sounds awesome!

**Comment by markubiak** [comment]
I've added a Linux flag for this, latest commit is in dev branch.  About to work on a Windows equivalent.  Is adding Mac support for this a possibility?

**Comment by lalo2302** [comment]
I think so, I will work on it

**Comment by markubiak** [comment]
Any updates on the OSX autostart?

**Comment by lalo2302** [comment]
No sorry, but maybe in two weeks I'll have it

**Comment by markubiak** [comment]
I'm going to move forward with --auto-startup as a GNU/Linux only feature.  If you'd like to work on a Mac OS X equivalent I'll leave the issue open, otherwise I will close it.
