### ISSUE TITLE
Automatic configuration of setcommand doesn't work on Lubuntu

### ISSUE THREAD

**Issue by inondle** [markubiak/wallpaper-reddit#28]
Using Lubuntu 16.06 the setcommand configuration field isn't automatically set. The command to change a wallpaper is `pcmanfm -w /path/to/image`. I also think there should be some better docs for how to add your own set command to the configuration file. Otherwise you have to dig around the code to figure out how the command gets interpreted.

**Comment by markubiak** [comment]
Alright, I'll add some more documentation on how to use the setcommand parameter.  Could you please provide me with the $DESKTOP_SESSION variable for Lubuntu?  Ex. `echo $DESKTOP_SESSION`

**Comment by inondle** [comment]
The variable is 'Lubuntu'.

**Comment by markubiak** [comment]
Closed, thank you for the PR.
