### ISSUE TITLE
Return status of os.system calls are not checked for successful execution.

### ISSUE THREAD

**Issue by inondle** [markubiak/wallpaper-reddit#29]
When wallpaper-reddit runs the `linux_wallpaper()` call it doesn't check the return status of any of the `os.system()` calls. If there is an unsuccessful `os.system()` call then the program will still report that the command was run even though the verbose mode will print error messages for unrecognized arguments.

**Comment by markubiak** [comment]
Good catch.  I'm not quite following what you mean about verbose mode, however.

**Comment by inondle** [comment]
With the `-v` argument it will say that there was some sort of problem running the setcommand (eg. Unrecognized arguments, etc). Without the verbose mode turned on the script simply reports that the command run whether it returns successfully or not.

**Comment by markubiak** [comment]
Alright, I've committed a change that checks to make sure all os.system() commands return an exit code of 0.  Seems to work on my testing.  It's in the dev branch, commit dd4adc8993da04261b37ed5b62973251efe11d5c

**Comment by markubiak** [comment]
I'm going to reopen this because I'd really like to work on migration from os.system() to subprocess.  Subprocess actually throws errors and other nice things.  I'm going to try to push out an update in the next week with this migration and Pillow 4 compatibility

**Comment by markubiak** [comment]
Moved to main branch, closed.
