### ISSUE TITLE
xfce setcommand

### ISSUE THREAD

**Issue by shigox23** [markubiak/wallpaper-reddit#39]
I was able to fix the "Your DE could not be detected to set the wallpaper." With the following 

`setcommand = xfconf-query -c xfce4-desktop -p /backdrop/screen0/monitor0/workspace0/last-image -s /home/####/.wallpaper/wallpaper.jpg` 

Where the backdrop is found following the instructions below: 
> To determine the correct location of the backdrop entry, run:
> `xfconf-query -c xfce4-desktop -m`
> ...and then change the wallpaper using the normal desktop dialog (or thunar's "set as wallpaper"). This will show you which xfconf setting was changed to display the image. Adjust your script to use this location.
> Thanks to -- numzob

and #### is replaced by your username.

**Comment by markubiak** [comment]
Thank you for filing this.  XFCE should be automatically detected -- can you provide the output of `echo $DESKTOP_SESSION`?  What distribution are you using?

Mark

**Comment by markubiak** [comment]
Any chance you could run that command for me?

**Comment by rolandoislas** [comment]
I experienced this running XFCE as well on Debian Stretch 9.2 with LightDM as the display manager.

```
> echo $DESKTOP_SESSION
lightdm-xsession
```

**Comment by markubiak** [comment]
I don't think I can say that lightdm is tied to xfce; people using lightdm could just as well be using another desktop.  Sorry, I'm gonna close this one.  If you can find another good way to check for XFCE please reopen this!
