### ISSUE TITLE
Doesn't work well with images from imgur 

### ISSUE THREAD

**Issue by advance512** [markubiak/wallpaper-reddit#4]
And doesn't identify them as such, either

**Comment by markubiak** [comment]
I've had a fix for this in the Dev branch for awhile now.  Could you try it and see if it works?  As as note, in the update ~/.wallpaper/wallpaper is now ~/wallpaper/wallpaper.jpg. this was added for Windows support.

**Comment by markubiak** [comment]
Fix commited to Master branch and is included in release v2.0.
