### ISSUE TITLE
i3 setcommand

### ISSUE THREAD

**Issue by mpasa** [markubiak/wallpaper-reddit#41]
i3 tiling window manager (https://github.com/i3/i3) seems to not be supported. 

`echo $DESKTOP_SESSION` outputs `i3`

i3 does not provide a way to change the wallpaper directly (https://faq.i3wm.org/question/6/how-can-i-set-a-desktop-background-image-in-i3.1.html). A lot of people use `feh`, but it needs to be previously installed.

`setcommand = feh --bg-scale /home/####/.wallpaper/wallpaper.jpg`

`####` is replaced by your username.

**Comment by markubiak** [comment]
Resolved by PR #45
