### ISSUE TITLE
Configuration file is not used in i3

### ISSUE THREAD

**Issue by grandpancaker** [markubiak/wallpaper-reddit#50]
Hi, i am trying to set up wallpaper-reddit in Arch i3, all is working great but sadly i can't force it to use config '~/.config/wallpaper-reddit/wallpaper-reddit.conf'. Have you maybe consider adding an optional argument like '-c --config' to specify manually path to the configuration file?
or maybe is there some workaround?
Love your work and sorry for trouble :)

**Comment by markubiak** [comment]
That's super weird, because that config file is the default. You shouldn't have to specify anything... Maybe there's a typo in the config?

**Comment by grandpancaker** [comment]
My mistake, there was a typo. An argument like that would be still useful but definitely it is not urgent feature.
