### ISSUE TITLE
Not enough data to read image dimensions

### ISSUE THREAD

**Issue by lundal** [markubiak/wallpaper-reddit#6]
Identify is having problems with reading the image dimensions for many images when only supplied with the first 1000 bytes (the error is "identify: no decode delegate for this image format `' @ error/constitute.c/ReadImage/501"). Increasing the request size in check_dimensions() solves the problem. I am unsure how much is needed to cover all cases, but 4096 bytes appears to work fine.

**Comment by markubiak** [comment]
Yes, this is a very strange issue with JPEG files I've been struggling to find a real solution to.  It seems every image needs a different amount of data to properly find dimensions.  4096 is on the high end of that scale, while the current 1000 is admittedly on the very low end.  I'll up the headers to 4096 on the main branch, which should grab significantly more images, but still not _all_.

**Comment by lundal** [comment]
It might be that identify needs to read the entire jpeg header, which could be many KB depending on the file. A possible solution could be to incrementally download more of the file until identify can parse it. Say, download 256 bytes, try identify, then 1KB, try again, then 4KB, and so on (until a maximum size). It's not very elegant and it introduces latency, but it should fix the problem while keeping bandwidth down.
