### ISSUE TITLE
Make the script XDG Compliant

### ISSUE THREAD

**Issue by YuvalDahn** [markubiak/wallpaper-reddit#60]
According to [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
>  There is a single base directory relative to which user-specific data files should be written. This directory is defined by the environment variable `$XDG_DATA_HOME`. 
>  There is a single base directory relative to which user-specific non-essential (cached) data should be written. This directory is defined by the environment variable `$XDG_CACHE_HOME`. 
>  `$XDG_DATA_HOME` defines the base directory relative to which user specific data files should be stored. If `$XDG_DATA_HOME` is either not set or empty, a default equal to `$HOME/.local/share` should be used. 
>  `$XDG_CACHE_HOME` defines the base directory relative to which user specific non-essential data files should be stored. If `$XDG_CACHE_HOME` is either not set or empty, a default equal to `$HOME/.cache` should be used. 

Instead of making a `~/.wallpaper` directory inside one's home directory, I suggest creating this folder in either `~/.local/share/wallpaper/` or `~/.cache/wallpaper/`, and possibly also check if `$XDG_DATA_HOME` is defined and if it is use it.

**Comment by YuvalDahn** [comment]
nvm, I now see it was changed in the v4 branch

**Comment by markubiak** [comment]
Yes, I was working on this in the v4 branch. Unfortunately, I've moved onto other projects at this time.
